#!/bin/bash

if [ "$(git rev-parse --abbrev-ref HEAD)" == "master" ]; then

    LAYOUT_PREFIX='---\nlayout: index\n---\n'

    make webrelease

    git checkout gh-pages

    git checkout master -- README.md
    echo -e $LAYOUT_PREFIX > index.md
    cat README.md >> index.md
    rm README.md

    git checkout master -- web
    rm -r javascripts
    mv web/stylesheets/* stylesheets
    mv web/javascripts javascripts
    rm -r web

    git reset HEAD
    git add -A index.md javascripts stylesheets
    git commit -m "Sync gh-pages with master"

    git checkout master
fi
